---
title: "read_ema_data"
author: "Ilaria Colpizzi"
date: "23/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Loading libraries

```{r}
  library(psych) # for describing the data
  library(plyr) #for data manipulation
  library(ggplot2) # for data visualization
  library(sjPlot) # for model visualization
  library(dplyr)
  library(rio)
  library(here)
  library(purrr)
  library(lubridate)
  library(lme4)
  
# devtools::install_github("wviechtb/esmpack")
  library(esmpack)
```

# Data preparation and inspection

## Data loading 

```{r}
dir <- here("data", "raw")

file_names <- as.character(list.files(path=dir))
n_files <- length(file_names)

d_list <- list()

for (index_file in 1:n_files) {
  
  d1  <- read.csv(here("data", "raw", file_names[index_file]), header = FALSE)
  
  # get subject code
  subj_code <- d1[3, 2]
  
  # remove first two columns, which contain the times when the app was open and
  # the time when the app was closed.
  d2 <- d1[-(1:3), -c(1, 2)]
  
  # The responses are stored in the rows 2, 5, 8, ...
  # index_resp is an index that select the rows with the responses.
  index_resp <- seq(2, nrow(d2), by = 3)
  
  # Each row of d2 (which contains the responses to the 5 items at time t) is 
  # saved in the j-th element of the list1 list.
  list1 <- NULL
  j <- 1
  for(i in index_resp) {
    list1[[j]] <- d2[i, ]
    j = j+1
  }
  
  # Convert to data.frame
  df <- do.call(rbind.data.frame, list1)
  # df <- temp %>% 
  #   dplyr::select(!V8)
  
  # Change the names of the columns
  colnames(df) <- 
    c("context", "nervous", "upset", "satisfied", "happy", 
      "scs_pos_1", "scs_neg_2", "scs_pos_3", "scs_neg_4", "scs_neg_5", "scs_pos_6", "scs_pos_7", "scs_neg_8")
  # Add subj_code.
  df$subj_code <- subj_code
  
  # The same for the times of the responses (rows 3, 6, 9, ...)
  index_time <- seq(3, nrow(d2), by = 3)
  list_time <- NULL
  j <- 1
  for(i in index_time) {
    list_time[[j]] <- d2[i, ]
    j = j+1
  }
df_time <- do.call(rbind.data.frame, list_time)
  # df_time <- temp %>% 
  #   dplyr::select(!V8)
  
  colnames(df_time) <- 
    c("t1", "t2", "t3", "t4", "t5", "t6", "t7", "t8", "t9", "t10", "t11", 
      "t12", "t13")
  
  dat_time <- df_time %>% 
    purrr::map_dfr(ymd_hms)
  
  d <- cbind(df, dat_time)
  
  d_list[[index_file]] <- d
}
```

# convert list into data.frame

```{r}
mydat <- do.call(rbind.data.frame, d_list)

mydat[, 1:13] <- mydat[, 1:13] %>%
  purrr::map_dfr(as.numeric)
```


# Save processed data 

```{r}
saveRDS(
  mydat,
  here::here(
    "data", "processed", "6subj_ema_data.RDS"
  )
)
```

```{r}
View(mydat)
```

```{r}
summary(mydat)
```

# Date 

```{r}
mydat$date <- date(mydat$t1)
```

# Delete wrong days 

```{r}
mydat1 <- filter(mydat, !(date == "2022-03-31") & !(date == "2022-04-21")) %>%
  filter(!(date == "2022-04-28"))
```

```{r}
mydat1$date <- factor(mydat1$date)
mydat1$date <- forcats::fct_recode(
  mydat1$date,
  "1" = "2022-04-02",
  "2" = "2022-04-09", 
  "3" = "2022-04-16", 
  "4" = "2022-04-23", 
  "5" = "2022-04-30", 
  "6" = "2022-05-07", 
  "7" = "2022-05-14", 
  "8" = "2022-05-21",
  "9" = "2022-05-28" 
)
```


# Determine the time window of each administration. The function hour() returns
# the number of the hour minus 2 (so, I summed + 2)

```{r}
time_window <- rep(NA, length(mydat1$t1))
for(i in 1:length(mydat1$t1)){
  if (hour(mydat1$t1)[i] + 2 < 12) {
    time_window[i] <- 1
  } else if ((hour(mydat1$t1)[i] + 2 > 14) & (hour(mydat1$t1)[i] + 2 < 16)) {
    time_window[i] <- 2
  } else if ((hour(mydat1$t1)[i] + 2 > 16) & (hour(mydat1$t1)[i] + 2 < 18)) {
    time_window[i] <- 3
  } else if ((hour(mydat1$t1)[i] + 2 > 18) & (hour(mydat1$t1)[i] + 2 < 20)) {
    time_window[i] <- 4
  } else if ((hour(mydat1$t1)[i] + 2 > 20) & (hour(mydat1$t1)[i] + 2 < 22)) {
    time_window[i] <- 5
  }  else {
    time_window[i] <- 999
  }
  # print(i)
}
```

```{r}
mydat1$time_window <- time_window
```

### convert subj_code from string to number 

```{r}
grpid = function(x) match(x, unique(x))
  mydat1 <- mydat1 %>% 
    mutate(id = group_indices(., subj_code) %>% grpid)
```

```{r}
good_cols <- c(
  "id", "time_window", "date", "context", "nervous", "upset", "satisfied", "happy", 
      "scs_pos_1", "scs_neg_2", "scs_pos_3", "scs_neg_4", "scs_neg_5", "scs_pos_6", "scs_pos_7", "scs_neg_8")
```

```{r}
mydat2 <- mydat1 %>% 
  dplyr::select(all_of(good_cols))

thedat <- mydat2 %>% 
  mutate_if(is.numeric, round)
```

```{r}
View(mydat2)
```

```{r}
saveRDS(
  mydat2,
  here::here(
    "data", "processed", "6_subj_ema_data_processed.RDS"
  )
)
```

## Data inspection 

```{r}
str(mydat2)

describe(mydat2)

```


